const { ApplicationCommandOptionType, EmbedBuilder, AttachmentBuilder } = require("discord.js");
const { createCanvas, loadImage } = require("@napi-rs/canvas");

const MOJANG_PROFILE_URL = "https://api.mojang.com/users/profiles/minecraft";
const MCSRVSTAT_URL = "https://api.mcsrvstat.us/3";

const withTimeout = async (url, options = {}, timeoutMs = 10000) => {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    return await fetch(url, {
      ...options,
      signal: controller.signal
    });
  } finally {
    clearTimeout(timeout);
  }
};

const formatUuid = (uuid) => {
  if (!uuid || uuid.length !== 32) return uuid;
  return `${uuid.slice(0, 8)}-${uuid.slice(8, 12)}-${uuid.slice(12, 16)}-${uuid.slice(16, 20)}-${uuid.slice(20)}`;
};

const isHttpUrl = (value) => typeof value === "string" && /^https?:\/\//i.test(value);

const drawRoundedRect = (ctx, x, y, width, height, radius) => {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.lineTo(x + width - radius, y);
  ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
  ctx.lineTo(x + width, y + height - radius);
  ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
  ctx.lineTo(x + radius, y + height);
  ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
  ctx.lineTo(x, y + radius);
  ctx.quadraticCurveTo(x, y, x + radius, y);
  ctx.closePath();
};

const drawCardBase = (ctx, width, height) => {
  const bg = ctx.createLinearGradient(0, 0, width, height);
  bg.addColorStop(0, "#1b1330");
  bg.addColorStop(0.5, "#312e81");
  bg.addColorStop(1, "#1e1b4b");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, width, height);

  const glow = ctx.createRadialGradient(150, 120, 40, 150, 120, 280);
  glow.addColorStop(0, "rgba(167, 139, 250, 0.42)");
  glow.addColorStop(1, "rgba(167, 139, 250, 0)");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, width, height);

  drawRoundedRect(ctx, 24, 24, width - 48, height - 48, 22);
  ctx.fillStyle = "rgba(30, 27, 75, 0.72)";
  ctx.fill();
  ctx.strokeStyle = "rgba(196, 181, 253, 0.35)";
  ctx.lineWidth = 2;
  ctx.stroke();

  ctx.save();
  drawRoundedRect(ctx, 26, 26, width - 52, height - 52, 20);
  ctx.clip();
};

const wrapLines = (ctx, text, maxWidth, maxLines) => {
  const words = String(text || "").split(/\s+/);
  const lines = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (ctx.measureText(candidate).width > maxWidth) {
      if (current) lines.push(current);
      current = word;
      if (lines.length >= maxLines - 1) break;
    } else {
      current = candidate;
    }
  }

  if (lines.length < maxLines && current) lines.push(current);
  if (lines.length === maxLines && words.length > 0) {
    const last = lines[maxLines - 1];
    if (ctx.measureText(last).width > maxWidth - 18) {
      lines[maxLines - 1] = `${last.slice(0, Math.max(0, last.length - 4))}...`;
    }
  }

  return lines;
};

const buildPlayerCard = async (name, uuid) => {
  const width = 1000;
  const height = 380;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  drawCardBase(ctx, width, height);

  const avatar = await loadImage(`https://mc-heads.net/avatar/${encodeURIComponent(name)}/256`);
  const body = await loadImage(`https://mc-heads.net/body/${encodeURIComponent(name)}/right`);

  const avatarSize = 170;
  const avatarX = 65;
  const avatarY = 105;

  ctx.save();
  ctx.beginPath();
  ctx.arc(avatarX + avatarSize / 2, avatarY + avatarSize / 2, avatarSize / 2, 0, Math.PI * 2);
  ctx.closePath();
  ctx.clip();
  ctx.drawImage(avatar, avatarX, avatarY, avatarSize, avatarSize);
  ctx.restore();

  ctx.strokeStyle = "rgba(167, 139, 250, 0.95)";
  ctx.lineWidth = 6;
  ctx.beginPath();
  ctx.arc(avatarX + avatarSize / 2, avatarY + avatarSize / 2, avatarSize / 2 + 2, 0, Math.PI * 2);
  ctx.stroke();

  ctx.fillStyle = "#ede9fe";
  ctx.font = "700 52px Sans";
  ctx.fillText(name, 275, 140);

  ctx.fillStyle = "#c4b5fd";
  ctx.font = "600 22px Sans";
  ctx.fillText("Minecraft Player", 278, 178);

  const shortUuid = String(uuid).slice(0, 8);
  ctx.fillStyle = "rgba(221, 214, 254, 0.8)";
  ctx.font = "500 15px Monospace";
  ctx.fillText(`id ${shortUuid}...`, 278, 228);

  drawRoundedRect(ctx, 278, 286, 410, 44, 14);
  ctx.fillStyle = "rgba(49, 46, 129, 0.9)";
  ctx.fill();
  ctx.fillStyle = "#c4b5fd";
  ctx.font = "600 18px Sans";
  ctx.fillText("Generated by 404 Bot", 300, 314);

  const sourceX = 8;
  const sourceY = 0;
  const sourceW = Math.max(1, body.width - 16);
  const sourceH = Math.floor(body.height * 0.58);
  ctx.globalAlpha = 0.95;
  ctx.drawImage(body, sourceX, sourceY, sourceW, sourceH, width - 360, 30, 320, 330);
  ctx.globalAlpha = 1;
  ctx.restore();

  return canvas.toBuffer("image/png");
};

const buildServerCard = async ({ host, port, status, version, players, motd }) => {
  const width = 1000;
  const height = 380;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  drawCardBase(ctx, width, height);

  ctx.fillStyle = "#ede9fe";
  ctx.font = "700 48px Sans";
  ctx.fillText("Minecraft Server", 66, 105);

  ctx.fillStyle = status === "Online" ? "#86efac" : "#fda4af";
  ctx.font = "700 28px Sans";
  ctx.fillText(status, 70, 145);

  ctx.fillStyle = "#c4b5fd";
  ctx.font = "600 22px Sans";
  ctx.fillText("Host", 70, 196);
  ctx.fillStyle = "#f5f3ff";
  ctx.font = "600 24px Monospace";
  ctx.fillText(host, 70, 224);

  ctx.fillStyle = "#c4b5fd";
  ctx.font = "600 21px Sans";
  ctx.fillText(`Port: ${port}`, 70, 264);
  ctx.fillText(`Version: ${version}`, 70, 296);
  ctx.fillText(`Players: ${players}`, 70, 328);

  drawRoundedRect(ctx, 520, 68, 420, 250, 20);
  ctx.fillStyle = "rgba(49, 46, 129, 0.9)";
  ctx.fill();
  ctx.strokeStyle = "rgba(196, 181, 253, 0.35)";
  ctx.lineWidth = 2;
  ctx.stroke();

  ctx.fillStyle = "#ddd6fe";
  ctx.font = "700 24px Sans";
  ctx.fillText("MOTD", 550, 106);

  ctx.fillStyle = "#f5f3ff";
  ctx.font = "500 20px Sans";
  const lines = wrapLines(ctx, motd || "No MOTD", 370, 7);
  let y = 138;
  for (const line of lines) {
    ctx.fillText(line, 550, y);
    y += 30;
  }

  ctx.restore();
  return canvas.toBuffer("image/png");
};

module.exports = {
  name: "minecraft",
  description: "Get Minecraft player or server info",
  options: [
    {
      name: "username",
      description: "Get info for a Minecraft player",
      type: ApplicationCommandOptionType.Subcommand,
      options: [
        {
          name: "name",
          description: "Minecraft username",
          type: ApplicationCommandOptionType.String,
          required: true
        }
      ]
    },
    {
      name: "server",
      description: "Get info for a Minecraft server",
      type: ApplicationCommandOptionType.Subcommand,
      options: [
        {
          name: "ip",
          description: "Minecraft server IP or domain",
          type: ApplicationCommandOptionType.String,
          required: true
        }
      ]
    }
  ],

  callback: async (client, interaction) => {
    const subcommand = interaction.options.getSubcommand();
    const username = subcommand === "username" ? interaction.options.getString("name", true) : null;
    const server = subcommand === "server" ? interaction.options.getString("ip", true) : null;

    await interaction.deferReply();

    try {
      if (username) {
        const profileRes = await withTimeout(`${MOJANG_PROFILE_URL}/${encodeURIComponent(username)}`);

        if (profileRes.status === 204 || profileRes.status === 404) {
          await interaction.editReply(`No Minecraft account found for \`${username}\`.`);
          return;
        }

        if (!profileRes.ok) {
          await interaction.editReply("Could not fetch Minecraft user info right now.");
          return;
        }

        const profile = await profileRes.json();
        const uuid = formatUuid(profile.id);
        const cardBuffer = await buildPlayerCard(profile.name || "Unknown", uuid || "Unknown");
        const cardAttachment = new AttachmentBuilder(cardBuffer, { name: "minecraft-player-card.png" });

        const embed = new EmbedBuilder()
          .setTitle("Minecraft Player Info")
          .setColor("#ff4fa3")
          .setThumbnail(`https://mc-heads.net/avatar/${encodeURIComponent(profile.name)}/256`)
          .setImage("attachment://minecraft-player-card.png")
          .addFields(
            { name: "Username", value: profile.name || "Unknown", inline: true },
            { name: "UUID", value: uuid || "Unknown", inline: false },
            { name: "NameMC", value: `https://namemc.com/profile/${encodeURIComponent(profile.name)}`, inline: false }
          )
          .setFooter({ text: "Source: Mojang API" });

        await interaction.editReply({ embeds: [embed], files: [cardAttachment] });
        return;
      }

      const serverRes = await withTimeout(`${MCSRVSTAT_URL}/${encodeURIComponent(server)}`);
      if (!serverRes.ok) {
        await interaction.editReply("Could not fetch Minecraft server info right now.");
        return;
      }

      const data = await serverRes.json();
      if (!data.online) {
        const serverCard = await buildServerCard({
          host: server,
          port: "Unknown",
          status: "Offline",
          version: "Unknown",
          players: "0/0",
          motd: "Server is currently offline."
        });
        const serverAttachment = new AttachmentBuilder(serverCard, { name: "minecraft-server-card.png" });

        const offlineEmbed = new EmbedBuilder()
          .setTitle("Minecraft Server Info")
          .setColor("#ff4fa3")
          .setImage("attachment://minecraft-server-card.png")
          .addFields(
            { name: "Server", value: server, inline: true },
            { name: "Status", value: "Offline", inline: true }
          )
          .setFooter({ text: "Source: mcsrvstat.us" });

        await interaction.editReply({ embeds: [offlineEmbed], files: [serverAttachment] });
        return;
      }

      const motd = data.motd?.clean?.join("\n") || "No MOTD";
      const playersOnline = data.players?.online ?? 0;
      const playersMax = data.players?.max ?? 0;
      const playerList = (data.players?.list || []).slice(0, 20).join(", ");
      const version = data.version || "Unknown";
      const host = data.hostname || data.ip || server;
      const port = data.port ? String(data.port) : "Unknown";
      const serverCard = await buildServerCard({
        host,
        port,
        status: "Online",
        version,
        players: `${playersOnline}/${playersMax}`,
        motd
      });
      const serverAttachment = new AttachmentBuilder(serverCard, { name: "minecraft-server-card.png" });

      const onlineEmbed = new EmbedBuilder()
        .setTitle("Minecraft Server Info")
        .setColor("#ff4fa3")
        .setImage("attachment://minecraft-server-card.png")
        .addFields(
          { name: "Server", value: host, inline: true },
          { name: "Port", value: port, inline: true },
          { name: "Status", value: "Online", inline: true },
          { name: "Version", value: version, inline: true },
          { name: "Players", value: `${playersOnline}/${playersMax}`, inline: true },
          { name: "MOTD", value: motd.slice(0, 1024), inline: false },
          { name: "Player List", value: playerList || "Hidden or unavailable", inline: false }
        )
        .setFooter({ text: "Source: mcsrvstat.us" });

      if (isHttpUrl(data.icon)) {
        onlineEmbed.setThumbnail(data.icon);
      }

      await interaction.editReply({ embeds: [onlineEmbed], files: [serverAttachment] });
    } catch (error) {
      console.log("Minecraft command error:", error);
      await interaction.editReply("Error while fetching Minecraft info.");
    }
  }
};
